server:
  port: 8088
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host:  127.0.0.1
    port: 6379
    password:
    timeout: 2000ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 300
        max-wait: -1ms
# 是否启动swagger
swagger:
  enable: true